import type { BadgeData } from './types';
export declare const MAJOR_FINDING_BADGE: BadgeData;
export declare const INVISIBLE_SMALL_AREAS_BADGE: BadgeData;
export declare const SMOOTHED_DATA_BADGE: BadgeData;
export declare const COMPARISON_AVERAGE_BADGE: BadgeData;
export declare const CAN_FILTER_BADGE: BadgeData;
export declare const BACKGROUND_READING_BADGE: BadgeData;
export declare const OPEN_DATA_BADGE: BadgeData;
export declare const RAW_DATA_AVAILABLE_BADGE: BadgeData;
export declare const INTERACTIVE_BADGE: BadgeData;
export declare const PER_CAPITA_MAP_BADGE: BadgeData;
export declare const MODELLED_DATA_BADGE: BadgeData;
export declare const CORRELATION_NOT_CAUSATION_BADGE: BadgeData;
export declare const AGGREGATED_DATA_BADGE: BadgeData;
export declare const BOX_PLOTS_BADGE: BadgeData;
export declare const DISCRETE_SCALES_BADGE: BadgeData;
export declare const TOTAL_VALUES_BADGE: BadgeData;
export declare const SEF_BARCHART_BADGE: BadgeData;
export type SEFChartBadgeKind = 'distribution' | 'scatterplot';
export declare function makeSEFChartBadge(kind: SEFChartBadgeKind, areaName: string, compareTo: string): BadgeData;
