import type { BadgeIntent } from './types';
import type { BadgeIconName } from './icons/BadgeIcon.svelte';
export type BadgeRender = 'mini' | 'normal' | 'big';
export type BadgeBigStyle = 'round' | 'seal' | null;
export type BadgeVariant = 'filled' | 'outlined';
export type BigRoundVariant = 'solid' | 'ring' | 'double-ring' | 'stamp' | 'glow';
export type SealVariant = 'outlined' | 'filled';
export type BadgeInteraction = {
    id: string;
    label: string | null;
    render: BadgeRender;
    variant: BadgeVariant;
    intent: BadgeIntent | null;
    icon: BadgeIconName | null;
    bigStyle: BadgeBigStyle;
    bigVariant: BigRoundVariant | null;
    bigSize: number | null;
    sealVariant: SealVariant | null;
    sealSize: number | null;
    sealFontScale: number | null;
    rotationMs: number | null;
};
type BadgeFeedbackState = {
    open: boolean;
    interactedBadges: BadgeInteraction[];
    threshold: number;
};
export declare function markBadgeFeedbackShown(): void;
export declare const badgeFeedback: import("svelte/store").Writable<BadgeFeedbackState>;
export declare function recordBadgeInteraction(interaction: BadgeInteraction, threshold?: number): void;
export {};
